### ISSUE TITLE
duration as part of event signature

### ISSUE THREAD

**Issue by danigb** [soundio/sequence#1]
Hello, 

I've been following the progress of this for while. Good work! I wish something like this to get more or less standarized across different libraries. I'm interested in a declarative API to generate music and I've made a first attempt with [scorejs](https://github.com/danigb/scorejs) and know I'm planning to rewrite a second version and I think it would be nice to follow your specification.

One problem that bothers me is that in scorejs the duration play an important role, the same as time, in order to perform events transformations without knowing the type of the events, and in your specification, the duration is not always present, so this kind of functionallity is harder to implement.

Something like this would made the things much easier:

`event = [ time, dur, type, data... ] // dur === null means no duration`

... but I'm open to any solution... what do you think?

**Comment by stephband** [comment]
Hi! ScoreJS looks like a nice project.

In MusicJSON v1, I had duration as a value that applied to all events. I was with you – I was building Scribe (which does this: http://labs.cruncher.ch/scribe/) and working with notes, and it made a lot of sense. To the point where I had to wonder why they'd missed duration out of event bundles in the OSC spec (http://opensoundcontrol.org/files/OSC-Demo.pdf), which MusicJSON is influenced by.

The problem is that not all types of events do logically have a duration, so I ended up with lots of events with duration 0, which just seems redundant.

Consider these events:

Tempo change
Parameter change
Pitch change

It's not even clear to me that notes should have a duration, or whether separate noteon / noteoff events should be specified. Having single note events with a duration is nice and readable, and makes the data easy to manipulate, but for real time recording, and for implementing sequencers (eg: https://sound.io/sequencer/), it adds some complexity.

I think there is no silver bullet. The choice is between having lots of redundant 0s (or nulls), or having to query the type to determine whether duration is 0. One of the aims of MusicJSON is to be small. Small but readable. Therefore I opted to get rid of redundancy.

I'm totally open to counter-arguments :)

**Comment by danigb** [comment]
Hi, 

thanks for the response. Yes, I know that it depends on the point of view of what are you trying to build. In fact, I've ended transforming duration in note-on, note-end events inorder to schedule the audio. No silver bullet. I understand also the point of the redundancy (although in my case, most or the events are notes or chords). 

Even so, I think have a duration fixed in position the advantage of apply time transformations that preserves position and duration without know the type of event. For me this is crucial, since I use an open event type definition, and every transformation can publish the events they want (for example, harmonic analisys). 

So, focusing in a viable solution, what about:

`event = [time, type, data...] | [time, dur, type, data...]`

I mean: if the second parameter is a string, it's the type and has no duration. Otherwise the second parameter is the duration.

What do you think?

**Comment by stephband** [comment]
> For me this is crucial, since I use an open event type definition, and every transformation can publish the events they want (for example, harmonic analisys).

I'm not sure I understand this. Are you saying that transformations can invent new event types and insert those events into a sequence? I can see why you'd want duration fixed.

> I mean: if the second parameter is a string, it's the type and has no duration. Otherwise the second parameter is the duration.

Hmm, Interesting. I'm going to reflect on that.

**Comment by danigb** [comment]
> I'm not sure I understand this.

Jejeje... yes, scorejs 'plugins' can create new type of events. For example, an harmony analisys plugin would add "chord function" events overlapping the "chord". I know this is out of your scope, but I have more like an abstract event pipeline with transformations (and some are time-transformations).

I hope it's more clear now...

**Comment by stephband** [comment]
This is a bit of a hypothetical question, but how would you propose to avoid event type clashes? If say, one of your plugins, or someone else's plugin for ScoreJS, started generating 'jump' events, and we later wanted to specify 'jump' events in MusicJSON – but to mean something else – how could we do that?

**Comment by danigb** [comment]
Hi stephband,

After thinking for a while about this, and even if I still think that duration in the event signature has more advantages than drawbacks, I realize that the scope of this project is narrower of that what I need. I was looking more like an AST for defining abstract music, and you are focusing in midi recording and playback (instead of transformation). I think I will keep my sequence data structure (that uses objects events instead of arrays, so extensibility is much easier) and I will export to music-json format.

Thanks for the feedback and for the specification. I will continue following it closely.
Saludos
Dani
